// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV-DPmLiwfYS4zajpXWHJs1isahcsh9t8',
    appId: '1:75630856613:web:a36ad5c1a62d3e8f22c04c',
    messagingSenderId: '75630856613',
    projectId: 'waos-4535f',
    authDomain: 'waos-4535f.firebaseapp.com',
    databaseURL: 'https://waos-4535f-default-rtdb.firebaseio.com',
    storageBucket: 'waos-4535f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV-DPmLiwfYS4zajpXWHJs1isahcsh9t8',
    appId: '1:75630856613:android:a36ad5c1a62d3e8f22c04c',
    messagingSenderId: '75630856613',
    projectId: 'waos-4535f',
    databaseURL: 'https://waos-4535f-default-rtdb.firebaseio.com',
    storageBucket: 'waos-4535f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-DPmLiwfYS4zajpXWHJs1isahcsh9t8',
    appId: '1:75630856613:ios:a36ad5c1a62d3e8f22c04c',
    messagingSenderId: '75630856613',
    projectId: 'waos-4535f',
    databaseURL: 'https://waos-4535f-default-rtdb.firebaseio.com',
    storageBucket: 'waos-4535f.firebasestorage.app',
    iosBundleId: 'com.example.proyxd',
  );
}
